project:
  type: website
  output-dir: docs
  resources:
  - "files/Lizbeth Gomez_7.20.24_CV.pdf"
website:
  title: "Lizbeth F. Gomez"
  google-analytics: "G-8FWX65NBJQ"
  site-url: "http://www.lizbethgomezf.com"
  navbar:
    search: false
    left:
      - href: about.qmd
      - href: publications.qmd
      - href: talks.qmd
      - href: teaching.qmd
      #  - text: Home
    right: 
      - text: CV
        href: files/Lizbeth Gomez_7.20.24_CV.pdf
    open-graph: true
format:
  html:
    theme:
      - quartz
      
execute:
  echo: false
  message: false
  warning: false
  freeze: auto


