---
title: "In 2050 we'll have flying cars"
date: 2026-04-07
description: "How does our future look like."
categories: [personal, climate]
---

As I am writing these stream of thoughts now that I am [[In my blogging era]], I keep making the mistake of typing 2016 instead of 2026. This has happened thrice, and every time I chuckle in a somewhat cynic way. as I backtrack, I think about 2016 and how great life was still then (pause here and sigh in contemplation). 

No doubt nostalgia is making me see things through rose-colored glasses. For instance, I recently learned 2016's Pokemon GO was a[ mining data operation](https://www.technologyreview.com/2026/03/10/1134099/how-pokemon-go-is-helping-robots-deliver-pizza-on-time/). So yeah, I know it wasn't all great. But at the time we didn't know. More importantly we still hadn't grappled with the reality that after a shred of progress we'd lower the bar to hell. 

But a more consequential question I now have is what does 2050 look like? What's the world going to be like then? In 2050 I will be 56 years old, younger than my mom's current age. Will the planet be worse off? Will we be used to experiencing extreme weather events? Will we normalize the suffering of people in the wake of climate disasters? Will billionaires have enough.

