---
title: "NAM Climate Grand Challenge"
date: 2026-04-08
description: "Why have I been sleeping on public transit"
categories: [events, climate]
---

How cool are trains, huh? As I travel back from the National Academy of Medicine's 2026 Grand Challenge Summit, I am eager to reflect on this event and the many tidbits of information now germinating in the inner crevices of my brain.

It had been a while since I had enjoyed a seminar as much as I did this one. I think part of the reason I enjoyed this year's summit was: 1) the sheer breadth of expertise from multiple disciplines; 2) the opportunities to network and meet people all working (and very much caring) for people's health in the context of climate and planetary health; and 3) that I got to commute via Amtrak to DC.

I had no real plans to attend this event (I actually didn't even know about it until a few days before), but sometimes the stars align and you just make it happen. In the hours before the event, as I was planning my travels to DC, I defaulted to the plan to drive the three and a half hours down. I was weighing whether to stay at a hotel, or to grin and bear seven hours of total roundtrip time on the road after a long day of soaking in information. It wasn't until I almost backed out of the whole thing that I realized cars are not the only way to get from point A to B. I could take the train.

This was exciting to me in many ways: I could work and write on the way down, save on gas, and on the way back I could get some shut-eye (which, for the record, I am not doing). I am actively writing this instead. But most importantly, it was exciting because it made sense. Going to a climate and health event via private car, when I could have easily taken public transit, would have been a little ironic.

I'm glad I didn't. I'm glad I'm typing this while commuting alongside a bunch of other people in a somewhat reliable mode of transportation, not adding to the emissions that are at the very core of the climate crisis.

You're probably thinking: [Why Bother?](https://www.nytimes.com/2008/04/20/magazine/20wwln-lede-t.html) My answer to you is the answer I had when I read that NYT Magazine article in 2013: the moment we diminish our own small efforts, or become pessimistic about climate, is the moment we have lost. And I don't know about you, but I ain't no loser.

